language: generic
sudo: required
services:
  - docker

# before install and scripts runs tests, if any fails then deploy won't happen
before_install:
  - docker build -t albertkol/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true albertkol/react-test npm test

after_success:
  - docker build -t albertkol/multi-client ./client
  - docker build -t albertkol/multi-nginx ./nginx
  - docker build -t albertkol/multi-server ./server
  - docker build -t albertkol/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push albertkol/multi-client
  - docker push albertkol/multi-nginx
  - docker push albertkol/multi-server
  - docker push albertkol/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-116287104556'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY